services:
  forum:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://zeragon-db:5432/zeragon-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 13415968273
    depends_on:
      - zeragon-db

  zeragon-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zeragon-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13415968273
    ports:
      - "5432:5432"